// knex seed file
// adds test data to the database (including the admin user)

exports.seed = function(knex) {
    // Deletes ALL existing entries
    return knex('t_account').del()
        .then(function() {
            return knex('t_account').insert([
                {
                    id: 1,
                    name: 'admin',
                    salt: 'f86ea46b',
                    password: '813c501417cca3661e9e5419571010361b9af5ffa99b0dac0346643bc29fffd9270ba3f4d088226787c925d4dbf8da36245a71ea760714d77942647f4d861fbe',
                    contact_name: 'Lisa Nierhaus',
                    email: 'lisa.nierhaus@gmail.com',
                    contact_phone: '089 1235679',
                    company_type: 'ibc',
                    status: 'accepted',
                    admin: true
                },
                {
                    id: 2,
                    name: 'Sapient',
                    salt: 'f86ea46b',
                    password: '813c501417cca3661e9e5419571010361b9af5ffa99b0dac0346643bc29fffd9270ba3f4d088226787c925d4dbf8da36245a71ea760714d77942647f4d861fbe',
                    contact_name: 'Wolf Ingomar Faecks',
                    email: 'info@sapient-unreal.de',
                    contact_phone: '089 1235679',
                    company_type: 'ibc',
                    status: 'accepted',
                    admin: false
                },
                {
                    id: 3,
                    name: 'Messe München',
                    salt: 'f86ea46b',
                    password: '813c501417cca3661e9e5419571010361b9af5ffa99b0dac0346643bc29fffd9270ba3f4d088226787c925d4dbf8da36245a71ea760714d77942647f4d861fbe',
                    contact_name: 'Max Mustermann',
                    email: 'info@messe-unreal.de',
                    contact_phone: '089 1235679',
                    company_type: 'ibc',
                    status: 'accepted',
                    admin: false
                },
                {
                    id: 4,
                    name: 'Hubert Burda',
                    salt: 'f86ea46b',
                    password: '813c501417cca3661e9e5419571010361b9af5ffa99b0dac0346643bc29fffd9270ba3f4d088226787c925d4dbf8da36245a71ea760714d77942647f4d861fbe',
                    contact_name: 'Erika Musterfrau',
                    email: 'info@burda-unreal.de',
                    contact_phone: '089 1235679',
                    company_type: 'ibc',
                    status: 'accepted',
                    admin: false
                },
                {
                    id: 5,
                    name: 'Pro7 Sat1',
                    salt: 'f86ea46b',
                    password: '813c501417cca3661e9e5419571010361b9af5ffa99b0dac0346643bc29fffd9270ba3f4d088226787c925d4dbf8da36245a71ea760714d77942647f4d861fbe',
                    contact_name: 'Ingo Herrmann',
                    email: 'info@pro7-unreal.de',
                    contact_phone: '089 1235679',
                    company_type: 'ibc',
                    status: 'accepted',
                    admin: false
                },
                {
                    id: 6,
                    name: 'Studentenberatung München',
                    salt: 'f86ea46b',
                    password: '813c501417cca3661e9e5419571010361b9af5ffa99b0dac0346643bc29fffd9270ba3f4d088226787c925d4dbf8da36245a71ea760714d77942647f4d861fbe',
                    contact_name: 'Manfred Mannheimer',
                    email: 'info@sbm-unreal.de',
                    contact_phone: '089 1235679',
                    company_type: 'ngo',
                    status: 'registered',
                    admin: false
                },
                {
                    id: 7,
                    name: 'BMW',
                    salt: 'f86ea46b',
                    password: '813c501417cca3661e9e5419571010361b9af5ffa99b0dac0346643bc29fffd9270ba3f4d088226787c925d4dbf8da36245a71ea760714d77942647f4d861fbe',
                    contact_name: 'Hannelohre Meißner',
                    email: 'info@bmw-unreal.de',
                    contact_phone: '089 1235679',
                    company_type: 'ngo',
                    status: 'registered',
                    admin: false
                },
                {
                    id: 8,
                    name: 'ProGlove',
                    salt: 'f86ea46b',
                    password: '813c501417cca3661e9e5419571010361b9af5ffa99b0dac0346643bc29fffd9270ba3f4d088226787c925d4dbf8da36245a71ea760714d77942647f4d861fbe',
                    contact_name: 'Thomas Kirchner',
                    email: 'founder@proglove-unreal.de',
                    contact_phone: '089 1235679',
                    company_type: 'startup',
                    status: 'registered',
                    admin: false
                },
                {
                    id: 9,
                    name: 'Siemens',
                    salt: 'f86ea46b',
                    password: '813c501417cca3661e9e5419571010361b9af5ffa99b0dac0346643bc29fffd9270ba3f4d088226787c925d4dbf8da36245a71ea760714d77942647f4d861fbe',
                    contact_name: 'Jette Mayer',
                    email: 'info@siemens-unreal.de',
                    contact_phone: '089 1235679',
                    company_type: 'startup',
                    status: 'declined',
                    admin: false
                }
            ]);
        }).then(function() {
            return knex('t_company').insert([
                {
                    id: 1,
                    account_id: 2,
                    company_name: 'SapientRazorfish',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Berlin, Dubai, Geneva, Paris, Turin',
                    employees: '5',
                    website: 'https://www.sapientrazorfish.com/',
                    kununu: 'https://www.kununu.com/de/sapientrazorfish',
                    field_of_activity: 'Digital Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"Farbenfrohe Testbeschreibung \",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":12,\"style\":\"color-rgb(44,130,201)\"},{\"offset\":12,\"length\":4,\"style\":\"color-rgb(226,80,65)\"},{\"offset\":16,\"length\":13,\"style\":\"color-rgb(65,168,95)\"}],\"entityRanges\":[],\"data\":{}},{\"key\":\"d0je4\",\"text\":\"mit\",\"type\":\"unordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":3,\"style\":\"color-rgb(44,130,201)\"}],\"entityRanges\":[],\"data\":{}},{\"key\":\"89nva\",\"text\":\"einer\",\"type\":\"unordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":5,\"style\":\"color-rgb(226,80,65)\"}],\"entityRanges\":[],\"data\":{}},{\"key\":\"2862b\",\"text\":\"Liste\",\"type\":\"unordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":5,\"style\":\"color-rgb(65,168,95)\"}],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 2,
                    account_id: 2,
                    company_name: 'Sapient Consulting',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapientconsulting.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 3,
                    account_id: 3,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 4,
                    account_id: 4,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 5,
                    account_id: 4,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 6,
                    account_id: 4,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 8,
                    account_id: 4,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 9,
                    account_id: 4,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 10,
                    account_id: 5,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 11,
                    account_id: 5,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 12,
                    account_id: 5,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 13,
                    account_id: 5,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 14,
                    account_id: 5,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 15,
                    account_id: 6,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 16,
                    account_id: 7,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 17,
                    account_id: 8,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                },
                {
                    id: 18,
                    account_id: 9,
                    company_name: 'dummy',
                    munich_address: 'Arnulfstrasse 60\n80335 Munich\nGermany',
                    locations: 'Boston, New York, Frankfurt, London',
                    employees: '5',
                    website: 'https://www.sapient.com/',
                    kununu: 'https://www.kununu.com/de/sapient-global-markets7',
                    field_of_activity: 'Consulting',
                    logo: '',
                    company_description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}"
                }
            ]);
        }).then(function() {
            return knex('t_recruiter').insert([
                {
                    id: 1,
                    account_id: 2,
                    recruiter_name: 'Jasmin Martensmeier',
                    recruiter_email: 'jmartensmeier@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Senior Manager Talent Acquisition',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Jasmin_Martensmeier',
                    linked_in: 'https://www.linkedin.com/in/jasmin-martensmeier-378893b'
                },
                {
                    id: 2,
                    account_id: 2,
                    recruiter_name: 'Carolin Chmielewski',
                    recruiter_email: 'cchmielewski@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Senior Recruiter & Employer Branding',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Carolin_Chmielewski',
                    linked_in: 'https://www.linkedin.com/in/carolin-chmielewski-44b597108'
                },
                {
                    id: 3,
                    account_id: 2,
                    recruiter_name: 'Melissa Beikirch',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 4,
                    account_id: 3,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 5,
                    account_id: 3,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 6,
                    account_id: 3,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 7,
                    account_id: 4,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 8,
                    account_id: 4,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 9,
                    account_id: 5,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 10,
                    account_id: 5,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 11,
                    account_id: 5,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 12,
                    account_id: 5,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 13,
                    account_id: 6,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 14,
                    account_id: 7,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 15,
                    account_id: 8,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                },
                {
                    id: 16,
                    account_id: 9,
                    recruiter_name: 'dummy',
                    recruiter_email: 'mbeikirch@sapient.com',
                    phone: '089 1235679',
                    mobile: '0172 1235679',
                    position: 'Recruiter',
                    location: 'München',
                    photo: '',
                    xing: 'https://www.xing.com/profile/Melissa_Beikirch',
                    linked_in: 'https://www.linkedin.com/in/melissa-beikirch-9b935b13a'
                }
            ]);
        }).then(function() {

            let now = new Date();
            let dayAfterTomorrow = new Date();
            dayAfterTomorrow.setDate(dayAfterTomorrow.getDate() + 2);
            let inSixtyDays = new Date();
            inSixtyDays.setDate(inSixtyDays.getDate() + 60);

            return knex('t_posting').insert([
                {
                    id: 1,
                    account_id: 2,
                    company_id: 1,
                    recruiter_id: 2,
                    title: 'Werkstudentenstelle Digitales Marketing',
                    start_of_employment: 'Ab Sofort',
                    contract_type: 'Werkstudent',
                    contract_duration: '6',
                    working_hours: '20h/Woche',
                    entry_level: 'Studenten',
                    place_of_employment: 'München',
                    application_link: 'https://sapient.taleo.net/careersection/84651/jobdetail.ftl?lang=en&job=229857',
                    field_of_employment: 'marketing',
                    pdf: false,
                    status: 'active',
                    description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}",
                    expiry_date: inSixtyDays.toISOString()
                },
                {
                    id: 2,
                    account_id: 2,
                    company_id: 1,
                    recruiter_id: 3,
                    title: 'Direkteinstieg Online Marketing',
                    start_of_employment: 'Nach Vereinbarung',
                    contract_type: 'Direkteinstieg',
                    contract_duration: 'indefinite',
                    working_hours: 'Vollzeit',
                    entry_level: 'Absolventen',
                    place_of_employment: 'München',
                    application_link: 'https://sapient.taleo.net/careersection/84651/jobdetail.ftl?lang=en&job=229857',
                    field_of_employment: 'marketing',
                    pdf: false,
                    status: 'active',
                    description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}",
                    expiry_date: inSixtyDays.toISOString()
                },
                {
                    id: 3,
                    account_id: 2,
                    company_id: 2,
                    recruiter_id: 1,
                    title: 'JUNIOR ARCHITECT ENTERPRISE APPLICATION DEVELOPMENT (m/f)',
                    start_of_employment: dayAfterTomorrow.toISOString(),
                    contract_type: 'Direkteinstieg',
                    contract_duration: 'indefinite',
                    working_hours: 'Vollzeit',
                    entry_level: 'Absolventen',
                    place_of_employment: 'München',
                    application_link: 'https://sapient.taleo.net/careersection/84651/jobdetail.ftl?lang=en&job=228060',
                    field_of_employment: 'itDev',
                    pdf: false,
                    status: 'active',
                    description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}",
                    expiry_date: inSixtyDays.toISOString()
                },
                {
                    id: 4,
                    account_id: 2,
                    company_id: 1,
                    recruiter_id: 2,
                    title: 'Software Architect Salesforce (m/w)',
                    start_of_employment: 'Ab Sofort',
                    contract_type: 'Direkteinstieg',
                    contract_duration: 'indefinite',
                    working_hours: 'Vollzeit',
                    entry_level: 'Absolventen',
                    place_of_employment: 'München',
                    application_link: 'https://sapient.taleo.net/careersection/84651/jobdetail.ftl?lang=en&job=228060',
                    field_of_employment: 'itDev',
                    pdf: false,
                    status: 'active',
                    description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}",
                    expiry_date: inSixtyDays.toISOString()
                },
                {
                    id: 5,
                    account_id: 2,
                    company_id: 2,
                    recruiter_id: 3,
                    title: 'Masterarbeit im Bereich Video & Audio im Netz',
                    start_of_employment: 'Ab Sofort',
                    contract_type: 'Werkstudent',
                    contract_duration: 'indefinite',
                    working_hours: '15 - 20 h/Woche',
                    entry_level: 'Masteranden',
                    place_of_employment: 'München',
                    application_link: 'https://sapient.taleo.net/careersection/84651/jobdetail.ftl?lang=en&job=228060',
                    field_of_employment: 'video',
                    pdf: false,
                    status: 'active',
                    description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}",
                    expiry_date: inSixtyDays.toISOString()
                },
                {
                    id: 6,
                    account_id: 3,
                    company_id: 3,
                    recruiter_id: 4,
                    title: 'Junior Customer Relations Officer',
                    start_of_employment: 'Ab Sofort',
                    contract_type: 'Direkteinstieg',
                    contract_duration: '12',
                    working_hours: '38 h/Woche',
                    entry_level: 'Absolventen',
                    place_of_employment: 'München',
                    application_link: 'https://sapient.taleo.net/careersection/84651/jobdetail.ftl?lang=en&job=228060',
                    field_of_employment: 'video',
                    pdf: false,
                    status: 'active',
                    description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}",
                    expiry_date: inSixtyDays.toISOString()
                },
                {
                    id: 7,
                    account_id: 3,
                    company_id: 3,
                    recruiter_id: 4,
                    title: 'Projektassistenz (m/w) electronica',
                    start_of_employment: inSixtyDays.toISOString(),
                    contract_type: 'Praktikum',
                    contract_duration: '6',
                    working_hours: '40 h/Woche',
                    entry_level: 'Studenten',
                    place_of_employment: 'München',
                    application_link: 'https://sapient.taleo.net/careersection/84651/jobdetail.ftl?lang=en&job=228060',
                    field_of_employment: 'video',
                    pdf: false,
                    status: 'active',
                    description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}",
                    expiry_date: inSixtyDays.toISOString()
                },
                {
                    id: 8,
                    account_id: 2,
                    company_id: 1,
                    recruiter_id: 1,
                    title: 'Werkstudent Creative Executive Assistant (m/w)',
                    start_of_employment: 'Ab Sofort',
                    contract_type: 'Werkstudent',
                    contract_duration: '6',
                    working_hours: '20 h/Woche',
                    entry_level: 'Studenten',
                    place_of_employment: 'München',
                    application_link: 'https://sapient.taleo.net/careersection/84651/jobdetail.ftl?lang=en&job=228060',
                    field_of_employment: 'video',
                    pdf: false,
                    status: 'active',
                    description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}",
                    expiry_date: dayAfterTomorrow.toISOString()
                },
                {
                    id: 9,
                    account_id: 2,
                    company_id: 2,
                    recruiter_id: 3,
                    title: 'Program Manager (m/w)',
                    start_of_employment: 'Ab Sofort',
                    contract_type: 'Direkteinstieg',
                    contract_duration: '12',
                    working_hours: '40 h/Woche',
                    entry_level: 'Absolventen',
                    place_of_employment: 'München',
                    application_link: 'https://sapient.taleo.net/careersection/84651/jobdetail.ftl?lang=en&job=228060',
                    field_of_employment: 'video',
                    pdf: false,
                    status: 'active',
                    description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}",
                    expiry_date: now.toISOString()
                },
                {
                    id: 10,
                    account_id: 2,
                    company_id: 2,
                    recruiter_id: 3,
                    title: 'Program Manager (m/w) - draft',
                    start_of_employment: 'Ab Sofort',
                    contract_type: 'Direkteinstieg',
                    contract_duration: '12',
                    working_hours: '40 h/Woche',
                    entry_level: 'Absolventen',
                    place_of_employment: 'München',
                    application_link: 'https://sapient.taleo.net/careersection/84651/jobdetail.ftl?lang=en&job=228060',
                    field_of_employment: 'video',
                    pdf: false,
                    status: 'deactivated',
                    description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}",
                    expiry_date: ''
                },
                {
                    id: 11,
                    account_id: 2,
                    company_id: 1,
                    recruiter_id: 1,
                    title: 'Werkstudent Creative Executive Assistant (m/w) - alt',
                    start_of_employment: 'Ab Sofort',
                    contract_type: 'Werkstudent',
                    contract_duration: '12',
                    working_hours: '20 h/Woche',
                    entry_level: 'Studenten',
                    place_of_employment: 'München',
                    application_link: 'https://sapient.taleo.net/careersection/84651/jobdetail.ftl?lang=en&job=228060',
                    field_of_employment: 'video',
                    pdf: false,
                    status: 'deactivated',
                    description: "{\"entityMap\":{},\"blocks\":[{\"key\":\"1hf1m\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}]}",
                    expiry_date: ''
                }
            ]);
        });
};
